@Library('mylib')_
pipeline
{
    agent any
    stages
    {
        stage('contdwnld_master')
        {
            steps
            {
                script
                {
                    cicd.gitdwnld("maven")
                }
            }
        }
        stage('contbuild_master')
        {
            steps
            {
                script
                {
                    cicd.mavenbuild()
                }
            }
        }
    }
}
